# Generated by Django 2.2.1 on 2020-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201230_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
