# Generated by Django 2.2.1 on 2021-01-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_address_apartment_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address',
        ),
    ]
