# Generated by Django 2.2 on 2020-11-03 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201001_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=datetime.datetime(2020, 11, 3, 17, 39, 54, 584279, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
