# Generated by Django 2.2.1 on 2021-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210301_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_final_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
