# Generated by Django 2.2.1 on 2021-03-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
